/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import da.helper.DialogHelper;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author BNC
 */
public class CauHinh extends javax.swing.JFrame {

    /**
     * Creates new form CauHinh
     */
    private Connection conn;
    String hos = null;
    String host = null;
    String hostp = null;
    String ertp = null;
    String patp = null;
    String hoa = "jdbc:sqlserver://localhost";
    String hob = ":1433;databaseName=duanfinalFPL";
    String ert = null;
    String pat = null;
    ArrayList info = new ArrayList<>();

    public CauHinh() throws ParseException {
        initComponents();
        File filee = new File("config_DB.txt");
        if (filee.exists()) {
            try {
                FileInputStream file = new FileInputStream("config_DB.txt");
                try (ObjectInputStream objIn = new ObjectInputStream(file)) {
                    info = (ArrayList) objIn.readObject();

                }
            } catch (IOException | ClassNotFoundException e) {
            }
            hostp = info.get(0).toString();
            ertp = info.get(1).toString();
            patp = info.get(2).toString();
            new dangnhap().setVisible(true);
        }
        setLocationRelativeTo(null);
    }
    

    public boolean Check() {
        if (txt_Host.getText().isEmpty()) {
            DialogHelper.alert(this, "Vui lòng nhập host !");
            txt_Host.requestFocus();
            return false;
        } else if (txt_ID.getText().isEmpty()) {
            DialogHelper.alert(this, "Vui lòng nhập ID !");
            txt_ID.requestFocus();
            return false;
        } else if (pas_Pass.getText().isEmpty()) {
            DialogHelper.alert(this, "Vui lòng nhập password !");
            pas_Pass.requestFocus();
            return false;
        }
        return true;
    }

    public ArrayList readFile() {
        File filee = new File("config_DB.txt");
        if (filee.exists()) {
            try {
                FileInputStream file = new FileInputStream("config_DB.txt");
                try (ObjectInputStream objIn = new ObjectInputStream(file)) {
                    info = (ArrayList) objIn.readObject();
                }
            } catch (IOException | ClassNotFoundException e) {
                e.printStackTrace();
            }
        }
        return info;
    }

    public void KetNoị() {
        hos = txt_Host.getText();
        host = hoa + "\\" + hos + hob;
        ert = txt_ID.getText();
        pat = pas_Pass.getText();
        if (Check() == true) {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                conn = DriverManager.getConnection(host, ert, pat);
                try {
                    // Ghi xuong file
                    info.add(host);
                    info.add(ert);
                    info.add(pat);
                    FileOutputStream file = new FileOutputStream("config_DB.txt");
                    try (ObjectOutputStream objOut = new ObjectOutputStream(file)) {
                        objOut.writeObject(info);
                        objOut.flush();
                    }
                } catch (IOException ex) {
                    Logger.getLogger(CauHinh.class.getName()).log(Level.SEVERE, null, ex);
                }
                DialogHelper.alert(this, "Kết nối thành công!");
                this.setVisible(false);
                new dangnhap().setVisible(true);
            } catch (ClassNotFoundException | SQLException e) {
                System.out.println(e);
                DialogHelper.alert(this, "Kết nối thất bại!");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_Host = new javax.swing.JTextField();
        txt_ID = new javax.swing.JTextField();
        lbl_Host = new javax.swing.JLabel();
        lbl_ID = new javax.swing.JLabel();
        lbl_Pass = new javax.swing.JLabel();
        pas_Pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btn_KetNoi = new javax.swing.JButton();
        btn_Thoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_Host.setText("Host :");

        lbl_ID.setText("ID :");

        lbl_Pass.setText("Password");

        pas_Pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pas_PassKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Host)
                    .addComponent(lbl_ID)
                    .addComponent(lbl_Pass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_Host)
                    .addComponent(txt_ID)
                    .addComponent(pas_Pass, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Host))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Pass)
                    .addComponent(pas_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Kết Nối");

        btn_KetNoi.setText("Kết Nối");
        btn_KetNoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KetNoiActionPerformed(evt);
            }
        });
        btn_KetNoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_KetNoiKeyPressed(evt);
            }
        });

        btn_Thoat.setText("Thoát");
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btn_KetNoi)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Thoat)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_KetNoi)
                    .addComponent(btn_Thoat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_KetNoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KetNoiActionPerformed
        KetNoị();
    }//GEN-LAST:event_btn_KetNoiActionPerformed

    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed
        DialogHelper.confirm(this, "Bạn có muốn thoát ?");
        System.exit(0);
    }//GEN-LAST:event_btn_ThoatActionPerformed

    private void btn_KetNoiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_KetNoiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            KetNoị();
            setVisible(false);
        }
    }//GEN-LAST:event_btn_KetNoiKeyPressed

    private void pas_PassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pas_PassKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            KetNoị();
            setVisible(false);
        }
    }//GEN-LAST:event_pas_PassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CauHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CauHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CauHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CauHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                File files = new File("config_DB.txt");
                if (files.exists()) {
                    try {
                        new CauHinh().setVisible(false);
                    } catch (ParseException ex) {
                        Logger.getLogger(CauHinh.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    try {
                        new CauHinh().setVisible(true);
                    } catch (ParseException ex) {
                        Logger.getLogger(CauHinh.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_KetNoi;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Host;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_Pass;
    private javax.swing.JPasswordField pas_Pass;
    private javax.swing.JTextField txt_Host;
    private javax.swing.JTextField txt_ID;
    // End of variables declaration//GEN-END:variables
}
